### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by lordekeen** [Weisl/Collider-Tools#438]
Hi, i'm trying to install the addon, and I keep getting the same error:

> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
>     mod = __import__(module_name)
> ModuleNotFoundError: No module named 'Collider-Tools-1'

With any version downloaded here, am i forgetting to do something?

**Comment by Weisl** [comment]
Hi @lordekeen,
The official releases are only uploaded on Blender Market and Gumroad. I have tested the releases on those platforms. Let me know if you encounter any issues with them. The GitHub releases contain the source code but are not necessarily the final tested product. 

- https://blendermarket.com/products/collider-tools
- https://weisl.gumroad.com/l/collider-tools?_gl=1*1ypbo12*_ga*MTI0OTI3MzkxNi4xNjg1MDk3OTk2*_ga_6LJN6D94N6*MTY4OTY2MTAxNC4xMi4wLjE2ODk2NjEwMTQuMC4wLjA.

cheers, 
Matthias

**Comment by namrog84** [comment]
FYI for those that came here later on.  The underlying problem is the name of the installed folder it gets installed to into Blender.

If you rename it (the main folder from `Collider-Tools-1.4.3` to `Collider-Tools` or equivalent.  This problem goes away.  

It just happens to be that the gumroad and blendermarket versions typically end up with slightly different packaging/parent folder names and doesn't face those issues.  

But as Weisl said, if you grab from the official tested sources, you don't have to make any changes yourself.
