### ISSUE TITLE
Error while enabling/installing

### ISSUE THREAD

**Issue by DarvanH548** [Weisl/Collider-Tools#483]
![image](https://github.com/Weisl/Collider-Tools/assets/75413047/54244fcd-e754-45bc-810f-1824e5eaf857)

**Comment by Shirosacid** [comment]
I guess its a problem between the addon and the Blender 4.1 version because im getting the same result

**Comment by Weisl** [comment]
This is due to the incorrect packaging of the Github version. The versions on BlenderMarket and Gumroad are packaged correctly and work without issues.

**Comment by DarvanH548** [comment]
This was made on purpose to people buy your addon lmao

**Comment by gentlemongoose** [comment]
there was a solution written in that post for it.
https://github.com/Weisl/Collider-Tools/issues/438

"FYI for those that came here later on. The underlying problem is the name of the installed folder it gets installed to into Blender.

If you rename it (the main folder from Collider-Tools-1.4.3 to Collider-Tools or equivalent. This problem goes away."

> This was made on purpose to people buy your addon lmao

**Comment by DarvanH548** [comment]
> there was a solution written in that post for it. #438
> 
> "FYI for those that came here later on. The underlying problem is the name of the installed folder it gets installed to into Blender.
> 
> If you rename it (the main folder from Collider-Tools-1.4.3 to Collider-Tools or equivalent. This problem goes away."
> 
> > This was made on purpose to people buy your addon lmao

Thank you very much
